# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-15 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_hde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128, verbose_name='Домен')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('api_key', models.CharField(max_length=256, verbose_name='API ключ')),
                ('department_id', models.PositiveSmallIntegerField(blank=True, help_text='Для добавленяи в запросы создания заявок, пользователя и т.д.', null=True, verbose_name='id департамента')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активны')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
                'verbose_name': 'Настройки',
            },
        ),
        migrations.DeleteModel(
            name='APICredentials',
        ),
    ]
