# Generated by Django 2.2.14 on 2020-10-07 13:27
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dj_hde', '0002_auto_20190715_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('department_id', models.PositiveSmallIntegerField(
                    blank=True,
                    help_text='Для добавления в запросы создания заявок, пользователя и т.д.',
                    null=True,
                    verbose_name='id департамента',
                )),
            ],
            options={
                'verbose_name_plural': 'Департамент',
                'verbose_name': 'Департаменты',
            },
        ),
        migrations.RemoveField(
            model_name='config',
            name='department_id',
        ),
        migrations.AddField(
            model_name='config',
            name='departments',
            field=models.ManyToManyField('Department', verbose_name='Департаменты'),
        ),
        migrations.AddField(
            model_name='config',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=models.deletion.CASCADE, to='sites.Site', verbose_name='ID Сайта'),
        ),
    ]
