# Generated by Django 2.2.14 on 2020-10-12 17:34
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('dj_hde', '0003_auto_20201007_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='site_id',
            new_name='site'
        ),
        migrations.AlterModelManagers(
            name='config',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        )
    ]
